Update prom libs
prometheus/statsd_exporter pull request #379
Opened 2021-06-07 14:35 UTC by sagikazarmark

2021-06-09 11:13 UTC, SuperQ requested changes
Some minor issues with the log library conversion.

2021-06-09 11:13 UTC, SuperQ commented on pkg/mapper/fsm/fsm.go
> +			level.Warn(logger).Log("msg", fmt.Sprintf("invalid match %s. cannot compile regex in mapping: %v", mapping, err))
This should be converted to structured logging style.

```suggestion
			level.Warn(logger).Log("msg", "Invalid match, cannot compile regex in mapping", "mapping", mapping, "err" err))
```

2021-06-09 11:13 UTC, SuperQ commented on pkg/mapper/fsm/fsm.go
> +							"the first will never be matched", r1, r2))
Similar here.

```suggestion
						level.Warn(logger).Log("msg", "match is a super set of match but in a lower order, the first will never be matched", "first_match", r1, "second_match", r2)
```

2021-06-09 11:13 UTC, SuperQ commented on pkg/mapper/fsm/fsm.go
> +					"matching performance may be degraded", r1))
```suggestion
				level.Warn(logger).Log("msg", "backtracking required because of match. Performance may be degraded", "match", r1)
```

2021-06-09 12:33 UTC, sagikazarmark commented
Thanks! I applied the suggested changes.

2021-06-09 12:42 UTC, SuperQ commented
Ahh, the fun of GitHub applying changes. You might want `git rebase -i origin/master` and squash the changes.

2021-06-09 12:44 UTC, SuperQ commented
Looks like I made a typo. :joy: 

```
pkg/mapper/fsm/fsm.go:253:110: missing ',' in argument list (typecheck)
			level.Warn(logger).Log("msg", "Invalid match, cannot compile regex in mapping", "mapping", mapping, "err" err))
			                                                                                                          ^
```

2021-06-09 12:45 UTC, sagikazarmark commented
Rebased, signed, typo fixed. Do you want me to squash as well?

2021-06-09 12:52 UTC, SuperQ approved these changes
LGTM, I'll leave it to @matthiasr to finish up.

2021-06-09 16:02 UTC, matthiasr approved these changes
Thank you!

2021-06-09 17:05 UTC, merged

2021-06-09 17:37 UTC, sagikazarmark commented
Any chance you could release a new version with the new dependencies? Thanks!

2021-06-10 07:34 UTC, matthiasr commented
[done!](https://github.com/prometheus/statsd_exporter/releases/tag/v0.21.0)

2021-06-10 11:12 UTC, sagikazarmark commented
Thanks!