Introduce original metric name as label
prometheus/statsd_exporter pull request #442
Opened 2022-06-17 10:32 UTC by pedro-stanaka

## Summary

This is my implementation for #438. I went with a naive approach here, I am always adding a new label at `exporter.go` if the metric has not labelset we create a new one and put the new label there.

2022-06-18 10:33 UTC, matthiasr requested changes
I don't want to make this the default for everyone, and I am uneasy about even hard coding the label value.

As I commented in #438, I found that this used to be possible by mapping the `$0` value into a label (and it still is, if you use the `regex` type match), so I would rather fix that for glob mappings than introduce a new behavior.

2022-06-18 10:33 UTC, matthiasr commented on .gitignore
> +.idea
Please add this to your global .gitignore, not every project

2022-06-20 06:03 UTC, pedro-stanaka commented
Thanks for the feedback on the issue #438 @matthiasr. I will close that now and try to work with the regex solution you presented. 👍

2022-06-20 09:07 UTC, closed without merging

2022-06-20 09:07 UTC, matthiasr commented
Oops got confused 😅